version: '2.1'
services:
  web:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app
    environment:
      WAIT_HOSTS: mongo:27017, elasticsearch:9200
  mongo:
    hostname: mongo
    image: "mongo:latest"
    ports:
      - "27017:27017"
  elasticsearch:
    hostname: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.2.2"
    ports:
      - "9200:9200"
      - "9300:9300"
